[2024-11-18T17:13:06.982+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.get_dataset manual__2024-11-18T17:07:57.830956+00:00 [queued]>
[2024-11-18T17:13:06.986+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.get_dataset manual__2024-11-18T17:07:57.830956+00:00 [queued]>
[2024-11-18T17:13:06.987+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-18T17:13:06.994+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): get_dataset> on 2024-11-18 17:07:57.830956+00:00
[2024-11-18T17:13:06.997+0000] {standard_task_runner.py:60} INFO - Started process 1042 to run task
[2024-11-18T17:13:06.999+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_recommender_dag_v3', 'get_dataset', 'manual__2024-11-18T17:07:57.830956+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/music_process.py', '--cfg-path', '/tmp/tmp8wca_31g']
[2024-11-18T17:13:07.000+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask get_dataset
[2024-11-18T17:13:07.026+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_recommender_dag_v3.get_dataset manual__2024-11-18T17:07:57.830956+00:00 [running]> on host 7526d0699246
[2024-11-18T17:13:07.065+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_recommender_dag_v3' AIRFLOW_CTX_TASK_ID='get_dataset' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T17:07:57.830956+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T17:07:57.830956+00:00'
[2024-11-18T17:13:07.066+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvazynj3sm --system-site-packages --python=python
[2024-11-18T17:13:07.071+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:13:07.398+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 116ms
[2024-11-18T17:13:07.399+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvazynj3sm, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T17:13:07.399+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T17:13:07.399+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T17:13:07.399+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T17:13:07.416+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvazynj3sm/bin/pip install -r /tmp/venvazynj3sm/requirements.txt
[2024-11-18T17:13:07.421+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:13:08.357+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvazynj3sm/requirements.txt (line 1))
[2024-11-18T17:13:08.358+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T17:13:08.359+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvazynj3sm/requirements.txt (line 2)) (2.0.3)
[2024-11-18T17:13:08.766+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvazynj3sm/requirements.txt (line 1))
[2024-11-18T17:13:08.767+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T17:13:08.768+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvazynj3sm/requirements.txt (line 1)) (0.10.0)
[2024-11-18T17:13:08.790+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvazynj3sm/requirements.txt (line 1))
[2024-11-18T17:13:08.791+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T17:13:08.845+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvazynj3sm/requirements.txt (line 2)) (2.8.2)
[2024-11-18T17:13:08.845+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvazynj3sm/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T17:13:08.850+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvazynj3sm/requirements.txt (line 2)) (2023.4)
[2024-11-18T17:13:08.851+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy>=1.20.3 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvazynj3sm/requirements.txt (line 2)) (1.24.4)
[2024-11-18T17:13:08.853+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvazynj3sm/requirements.txt (line 1)) (1.26.18)
[2024-11-18T17:13:08.854+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas==2.0.3->-r /tmp/venvazynj3sm/requirements.txt (line 2)) (1.16.0)
[2024-11-18T17:13:08.973+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T17:13:08.976+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T17:13:08.985+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T17:13:10.750+0000] {process_utils.py:190} INFO - Installing collected packages: botocore, s3transfer, boto3
[2024-11-18T17:13:10.750+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T17:13:10.754+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T17:13:10.758+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvazynj3sm
[2024-11-18T17:13:10.760+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T17:13:11.141+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T17:13:11.142+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T17:13:11.142+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvazynj3sm
[2024-11-18T17:13:11.143+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T17:13:11.163+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T17:13:11.164+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T17:13:11.165+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvazynj3sm
[2024-11-18T17:13:11.165+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T17:13:11.194+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T17:13:11.195+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T17:13:11.195+0000] {process_utils.py:190} INFO - Successfully installed boto3-1.28.0 botocore-1.31.85 s3transfer-0.6.2
[2024-11-18T17:13:11.268+0000] {process_utils.py:190} INFO - 
[2024-11-18T17:13:11.268+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T17:13:11.269+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T17:13:11.373+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvazynj3sm/bin/python /tmp/venv-callluxnkx2_/script.py /tmp/venv-callluxnkx2_/script.in /tmp/venv-callluxnkx2_/script.out /tmp/venv-callluxnkx2_/string_args.txt /tmp/venv-callluxnkx2_/termination.log
[2024-11-18T17:13:11.377+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T17:13:12.192+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T17:13:12.193+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callluxnkx2_/script.py", line 48, in <module>
[2024-11-18T17:13:12.193+0000] {process_utils.py:190} INFO -     res = get_dataset(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T17:13:12.193+0000] {process_utils.py:190} INFO -   File "/tmp/venv-callluxnkx2_/script.py", line 31, in get_dataset
[2024-11-18T17:13:12.193+0000] {process_utils.py:190} INFO -     endpoint_url=MINIO_ENDPOINT,
[2024-11-18T17:13:12.194+0000] {process_utils.py:190} INFO - NameError: name 'MINIO_ENDPOINT' is not defined
[2024-11-18T17:13:12.342+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
name 'MINIO_ENDPOINT' is not defined
[2024-11-18T17:13:12.344+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=spotify_recommender_dag_v3, task_id=get_dataset, execution_date=20241118T170757, start_date=20241118T171306, end_date=20241118T171312
[2024-11-18T17:13:12.351+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 24 for task get_dataset (Process returned non-zero exit status 1.
name 'MINIO_ENDPOINT' is not defined; 1042)
[2024-11-18T17:13:12.367+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T17:13:12.378+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
