[2024-11-18T18:14:00.459+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:08:37.853795+00:00 [queued]>
[2024-11-18T18:14:00.464+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:08:37.853795+00:00 [queued]>
[2024-11-18T18:14:00.464+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-18T18:14:00.471+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 18:08:37.853795+00:00
[2024-11-18T18:14:00.474+0000] {standard_task_runner.py:60} INFO - Started process 6944 to run task
[2024-11-18T18:14:00.475+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T18:08:37.853795+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmp1ah8ddly']
[2024-11-18T18:14:00.477+0000] {standard_task_runner.py:88} INFO - Job 76: Subtask train_challenger_model
[2024-11-18T18:14:00.505+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:08:37.853795+00:00 [running]> on host 98017b53a184
[2024-11-18T18:14:00.546+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T18:08:37.853795+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T18:08:37.853795+00:00'
[2024-11-18T18:14:00.547+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venv3qhm5871 --system-site-packages --python=python
[2024-11-18T18:14:00.551+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:14:00.881+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 121ms
[2024-11-18T18:14:00.882+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venv3qhm5871, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:14:00.882+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:14:00.883+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T18:14:00.883+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:14:00.901+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv3qhm5871/bin/pip install -r /tmp/venv3qhm5871/requirements.txt
[2024-11-18T18:14:00.905+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:14:01.832+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venv3qhm5871/requirements.txt (line 1))
[2024-11-18T18:14:01.833+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:14:01.871+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venv3qhm5871/requirements.txt (line 2))
[2024-11-18T18:14:01.872+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:14:01.873+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv3qhm5871/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:14:01.874+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venv3qhm5871/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:14:01.978+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:01.979+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:14:02.393+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venv3qhm5871/requirements.txt (line 1))
[2024-11-18T18:14:02.394+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:14:02.395+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venv3qhm5871/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:14:02.419+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venv3qhm5871/requirements.txt (line 1))
[2024-11-18T18:14:02.420+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:14:02.471+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:14:02.472+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:14:02.488+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2))
[2024-11-18T18:14:02.489+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:14:02.490+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:14:02.491+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:14:02.491+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:14:02.492+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:14:02.492+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:14:02.492+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (23.2)
[2024-11-18T18:14:02.493+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:14:02.493+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:14:02.494+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:14:02.494+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:14:02.495+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:14:02.495+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:14:02.496+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:14:02.513+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2))
[2024-11-18T18:14:02.514+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:14:02.515+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:14:02.516+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:14:02.516+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:14:02.516+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:14:02.517+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:14:02.518+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:14:02.570+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv3qhm5871/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:14:02.570+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venv3qhm5871/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:14:02.592+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv3qhm5871/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:14:02.592+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venv3qhm5871/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:14:02.627+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:02.628+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:14:02.644+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:02.645+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:14:02.663+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:02.664+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:14:02.685+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:02.686+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:14:02.704+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:02.705+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:14:02.706+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:14:02.750+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:02.751+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:14:02.779+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:02.781+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:14:02.803+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:02.804+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:14:02.953+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2))
[2024-11-18T18:14:02.954+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:14:02.972+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:02.973+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:14:02.974+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venv3qhm5871/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5)) (69.0.2)
[2024-11-18T18:14:02.975+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:14:03.000+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:03.001+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:14:03.022+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:03.023+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:14:03.024+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:14:03.048+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:03.049+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:14:03.050+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:14:03.112+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:03.113+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:14:03.120+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:14:03.124+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:14:03.127+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venv3qhm5871/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5)) (0.42.0)
[2024-11-18T18:14:03.132+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venv3qhm5871/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:14:03.147+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:14:03.147+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:14:03.164+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:14:03.191+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:14:03.194+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:14:03.218+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:14:03.219+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:14:03.219+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:14:03.220+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:14:03.229+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:14:03.230+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:14:03.274+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:14:03.275+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (3.6)
[2024-11-18T18:14:03.275+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:14:03.539+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:14:03.557+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:14:03.579+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:03.581+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:14:03.614+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5))
[2024-11-18T18:14:03.615+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:14:03.757+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venv3qhm5871/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:14:03.767+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:14:03.768+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:14:03.768+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5)) (4.9)
[2024-11-18T18:14:03.775+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:14:03.905+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:14:03.912+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venv3qhm5871/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:14:03.944+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:14:03.946+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:14:03.967+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:14:04.483+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:14:04.484+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:14:04.485+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:14:04.498+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:14:04.499+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:14:04.500+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:14:04.501+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:14:04.503+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:14:04.509+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:14:04.512+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:14:04.542+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:14:04.565+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:14:04.566+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:14:04.567+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:14:04.568+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:14:04.577+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:14:04.579+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:14:04.583+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:14:04.584+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:14:04.585+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:14:06.733+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:14:06.974+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:14:06.975+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:14:06.975+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv3qhm5871
[2024-11-18T18:14:06.976+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:14:07.252+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:14:07.253+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:14:07.254+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv3qhm5871
[2024-11-18T18:14:07.254+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:14:08.938+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:14:08.939+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:14:08.939+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv3qhm5871
[2024-11-18T18:14:08.939+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:14:09.334+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:14:09.336+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:14:09.336+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv3qhm5871
[2024-11-18T18:14:09.336+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:14:09.358+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:14:09.359+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:14:09.359+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv3qhm5871
[2024-11-18T18:14:09.359+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:14:09.556+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:14:09.557+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:14:09.558+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv3qhm5871
[2024-11-18T18:14:09.558+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:14:10.109+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:14:10.110+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:14:10.110+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venv3qhm5871
[2024-11-18T18:14:10.111+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:14:17.293+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:14:17.293+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:14:17.294+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:14:17.294+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:14:17.294+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:14:17.294+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:14:17.295+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:14:17.295+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:14:17.295+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T18:14:17.368+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:14:17.368+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T18:14:17.369+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:14:17.578+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venv3qhm5871/bin/python /tmp/venv-call51p9cxio/script.py /tmp/venv-call51p9cxio/script.in /tmp/venv-call51p9cxio/script.out /tmp/venv-call51p9cxio/string_args.txt /tmp/venv-call51p9cxio/termination.log
[2024-11-18T18:14:17.581+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:14:18.531+0000] {process_utils.py:190} INFO - 2024-11-18 18:14:18.531729: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T18:14:18.532+0000] {process_utils.py:190} INFO - 2024-11-18 18:14:18.532830: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:14:18.553+0000] {process_utils.py:190} INFO - 2024-11-18 18:14:18.553654: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:14:18.554+0000] {process_utils.py:190} INFO - 2024-11-18 18:14:18.553902: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T18:14:18.554+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T18:14:19.057+0000] {process_utils.py:190} INFO - 2024-11-18 18:14:19.057014: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T18:14:20.081+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T18:14:20.979+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:26 - loss: 0.3538 55/575 [=>............................] - ETA: 0s - loss: 0.1322  118/575 [=====>........................] - ETA: 0s - loss: 0.0909198/575 [=========>....................] - ETA: 0s - loss: 0.0704275/575 [=============>................] - ETA: 0s - loss: 0.0594355/575 [=================>............] - ETA: 0s - loss: 0.0521435/575 [=====================>........] - ETA: 0s - loss: 0.0468517/575 [=========================>....] - ETA: 0s - loss: 0.0428575/575 [==============================] - 1s 938us/step - loss: 0.0406 - val_loss: 0.0061
[2024-11-18T18:14:20.979+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T18:14:21.431+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0199 81/575 [===>..........................] - ETA: 0s - loss: 0.0182161/575 [=======>......................] - ETA: 0s - loss: 0.0181237/575 [===========>..................] - ETA: 0s - loss: 0.0175296/575 [==============>...............] - ETA: 0s - loss: 0.0172380/575 [==================>...........] - ETA: 0s - loss: 0.0166456/575 [======================>.......] - ETA: 0s - loss: 0.0162538/575 [===========================>..] - ETA: 0s - loss: 0.0158575/575 [==============================] - 0s 786us/step - loss: 0.0156 - val_loss: 0.0050
[2024-11-18T18:14:21.432+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T18:14:21.881+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0121 82/575 [===>..........................] - ETA: 0s - loss: 0.0129161/575 [=======>......................] - ETA: 0s - loss: 0.0124242/575 [===========>..................] - ETA: 0s - loss: 0.0120321/575 [===============>..............] - ETA: 0s - loss: 0.0118405/575 [====================>.........] - ETA: 0s - loss: 0.0117486/575 [========================>.....] - ETA: 0s - loss: 0.0115562/575 [============================>.] - ETA: 0s - loss: 0.0114575/575 [==============================] - 0s 781us/step - loss: 0.0113 - val_loss: 0.0041
[2024-11-18T18:14:21.881+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T18:14:22.332+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0130 78/575 [===>..........................] - ETA: 0s - loss: 0.0103158/575 [=======>......................] - ETA: 0s - loss: 0.0101239/575 [===========>..................] - ETA: 0s - loss: 0.0098318/575 [===============>..............] - ETA: 0s - loss: 0.0098397/575 [===================>..........] - ETA: 0s - loss: 0.0097478/575 [=======================>......] - ETA: 0s - loss: 0.0095548/575 [===========================>..] - ETA: 0s - loss: 0.0095575/575 [==============================] - 0s 785us/step - loss: 0.0095 - val_loss: 0.0037
[2024-11-18T18:14:22.333+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T18:14:22.789+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0068 78/575 [===>..........................] - ETA: 0s - loss: 0.0087156/575 [=======>......................] - ETA: 0s - loss: 0.0086233/575 [===========>..................] - ETA: 0s - loss: 0.0086311/575 [===============>..............] - ETA: 0s - loss: 0.0085390/575 [===================>..........] - ETA: 0s - loss: 0.0083464/575 [=======================>......] - ETA: 0s - loss: 0.0083541/575 [===========================>..] - ETA: 0s - loss: 0.0082575/575 [==============================] - 0s 794us/step - loss: 0.0082 - val_loss: 0.0033
[2024-11-18T18:14:22.790+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T18:14:23.240+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0106 84/575 [===>..........................] - ETA: 0s - loss: 0.0078166/575 [=======>......................] - ETA: 0s - loss: 0.0078237/575 [===========>..................] - ETA: 0s - loss: 0.0077321/575 [===============>..............] - ETA: 0s - loss: 0.0077403/575 [====================>.........] - ETA: 0s - loss: 0.0077485/575 [========================>.....] - ETA: 0s - loss: 0.0076549/575 [===========================>..] - ETA: 0s - loss: 0.0076575/575 [==============================] - 0s 782us/step - loss: 0.0076 - val_loss: 0.0028
[2024-11-18T18:14:23.240+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T18:14:23.692+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0084 79/575 [===>..........................] - ETA: 0s - loss: 0.0073153/575 [======>.......................] - ETA: 0s - loss: 0.0073229/575 [==========>...................] - ETA: 0s - loss: 0.0072308/575 [===============>..............] - ETA: 0s - loss: 0.0073382/575 [==================>...........] - ETA: 0s - loss: 0.0073459/575 [======================>.......] - ETA: 0s - loss: 0.0072538/575 [===========================>..] - ETA: 0s - loss: 0.0072575/575 [==============================] - 0s 785us/step - loss: 0.0071 - val_loss: 0.0027
[2024-11-18T18:14:23.692+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T18:14:24.148+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0074 79/575 [===>..........................] - ETA: 0s - loss: 0.0070160/575 [=======>......................] - ETA: 0s - loss: 0.0069237/575 [===========>..................] - ETA: 0s - loss: 0.0068311/575 [===============>..............] - ETA: 0s - loss: 0.0069384/575 [===================>..........] - ETA: 0s - loss: 0.0069459/575 [======================>.......] - ETA: 0s - loss: 0.0069535/575 [==========================>...] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 793us/step - loss: 0.0068 - val_loss: 0.0025
[2024-11-18T18:14:24.149+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T18:14:24.626+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0053 78/575 [===>..........................] - ETA: 0s - loss: 0.0066157/575 [=======>......................] - ETA: 0s - loss: 0.0067232/575 [===========>..................] - ETA: 0s - loss: 0.0068296/575 [==============>...............] - ETA: 0s - loss: 0.0067367/575 [==================>...........] - ETA: 0s - loss: 0.0067435/575 [=====================>........] - ETA: 0s - loss: 0.0067508/575 [=========================>....] - ETA: 0s - loss: 0.0067575/575 [==============================] - 0s 830us/step - loss: 0.0067 - val_loss: 0.0021
[2024-11-18T18:14:24.627+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T18:14:25.092+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0059 81/575 [===>..........................] - ETA: 0s - loss: 0.0065158/575 [=======>......................] - ETA: 0s - loss: 0.0066231/575 [===========>..................] - ETA: 0s - loss: 0.0066305/575 [==============>...............] - ETA: 0s - loss: 0.0066380/575 [==================>...........] - ETA: 0s - loss: 0.0067455/575 [======================>.......] - ETA: 0s - loss: 0.0067531/575 [==========================>...] - ETA: 0s - loss: 0.0067575/575 [==============================] - 0s 810us/step - loss: 0.0067 - val_loss: 0.0021
[2024-11-18T18:14:25.504+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 29s 97/719 [===>..........................] - ETA: 0s 203/719 [=======>......................] - ETA: 0s308/719 [===========>..................] - ETA: 0s412/719 [================>.............] - ETA: 0s516/719 [====================>.........] - ETA: 0s619/719 [========================>.....] - ETA: 0s719/719 [==============================] - 0s 489us/step
[2024-11-18T18:14:26.063+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 7s102/719 [===>..........................] - ETA: 0s203/719 [=======>......................] - ETA: 0s309/719 [===========>..................] - ETA: 0s411/719 [================>.............] - ETA: 0s516/719 [====================>.........] - ETA: 0s619/719 [========================>.....] - ETA: 0s719/719 [==============================] - 0s 479us/step
[2024-11-18T18:14:26.381+0000] {process_utils.py:190} INFO - /tmp/venv3qhm5871/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T18:14:26.395+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T18:14:26.395+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call51p9cxio/script.py", line 96, in <module>
[2024-11-18T18:14:26.395+0000] {process_utils.py:190} INFO -     res = train_challenger_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T18:14:26.396+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call51p9cxio/script.py", line 82, in train_challenger_model
[2024-11-18T18:14:26.396+0000] {process_utils.py:190} INFO -     model.save(model_path)
[2024-11-18T18:14:26.396+0000] {process_utils.py:190} INFO -   File "/tmp/venv3qhm5871/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
[2024-11-18T18:14:26.396+0000] {process_utils.py:190} INFO -     raise e.with_traceback(filtered_tb) from None
[2024-11-18T18:14:26.396+0000] {process_utils.py:190} INFO -   File "/tmp/venv3qhm5871/lib/python3.8/site-packages/tensorflow/python/lib/io/file_io.py", line 513, in recursive_create_dir_v2
[2024-11-18T18:14:26.397+0000] {process_utils.py:190} INFO -     _pywrap_file_io.RecursivelyCreateDir(compat.path_to_bytes(path))
[2024-11-18T18:14:26.397+0000] {process_utils.py:190} INFO - tensorflow.python.framework.errors_impl.PermissionDeniedError: /models; Permission denied
[2024-11-18T18:14:27.260+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
/models; Permission denied
[2024-11-18T18:14:27.262+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T180837, start_date=20241118T181400, end_date=20241118T181427
[2024-11-18T18:14:27.277+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 76 for task train_challenger_model (Process returned non-zero exit status 1.
/models; Permission denied; 6944)
[2024-11-18T18:14:27.307+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T18:14:27.320+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
