[2024-11-18T19:37:18.877+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.preprocess_and_split manual__2024-11-18T19:37:12.494221+00:00 [queued]>
[2024-11-18T19:37:18.881+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_recommender_dag_v3.preprocess_and_split manual__2024-11-18T19:37:12.494221+00:00 [queued]>
[2024-11-18T19:37:18.882+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-11-18T19:37:18.888+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): preprocess_and_split> on 2024-11-18 19:37:12.494221+00:00
[2024-11-18T19:37:18.891+0000] {standard_task_runner.py:60} INFO - Started process 820 to run task
[2024-11-18T19:37:18.893+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_recommender_dag_v3', 'preprocess_and_split', 'manual__2024-11-18T19:37:12.494221+00:00', '--job-id', '111', '--raw', '--subdir', 'DAGS_FOLDER/music_process.py', '--cfg-path', '/tmp/tmp8bju1751']
[2024-11-18T19:37:18.894+0000] {standard_task_runner.py:88} INFO - Job 111: Subtask preprocess_and_split
[2024-11-18T19:37:18.919+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_recommender_dag_v3.preprocess_and_split manual__2024-11-18T19:37:12.494221+00:00 [running]> on host 98017b53a184
[2024-11-18T19:37:19.572+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_recommender_dag_v3' AIRFLOW_CTX_TASK_ID='preprocess_and_split' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T19:37:12.494221+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T19:37:12.494221+00:00'
[2024-11-18T19:37:19.573+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvuu76orfh --system-site-packages --python=python
[2024-11-18T19:37:19.577+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T19:37:19.937+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 144ms
[2024-11-18T19:37:19.937+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvuu76orfh, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T19:37:19.938+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T19:37:19.938+0000] {process_utils.py:190} INFO -     added seed packages: pip==24.2, setuptools==75.2.0, wheel==0.44.0
[2024-11-18T19:37:19.938+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T19:37:19.956+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvuu76orfh/bin/pip install -r /tmp/venvuu76orfh/requirements.txt
[2024-11-18T19:37:19.960+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T19:37:20.806+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvuu76orfh/requirements.txt (line 1))
[2024-11-18T19:37:20.808+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T19:37:20.810+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvuu76orfh/requirements.txt (line 2)) (2.0.3)
[2024-11-18T19:37:20.810+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvuu76orfh/requirements.txt (line 3)) (1.3.2)
[2024-11-18T19:37:21.212+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvuu76orfh/requirements.txt (line 1))
[2024-11-18T19:37:21.214+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T19:37:21.216+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvuu76orfh/requirements.txt (line 1)) (0.10.0)
[2024-11-18T19:37:21.235+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvuu76orfh/requirements.txt (line 1))
[2024-11-18T19:37:21.236+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T19:37:21.258+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvuu76orfh/requirements.txt (line 2)) (2.8.2)
[2024-11-18T19:37:21.259+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz>=2020.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvuu76orfh/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T19:37:21.259+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvuu76orfh/requirements.txt (line 2)) (2023.4)
[2024-11-18T19:37:21.259+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy>=1.20.3 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvuu76orfh/requirements.txt (line 2)) (1.24.4)
[2024-11-18T19:37:21.265+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy>=1.5.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvuu76orfh/requirements.txt (line 3)) (1.10.1)
[2024-11-18T19:37:21.265+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvuu76orfh/requirements.txt (line 3)) (1.4.2)
[2024-11-18T19:37:21.266+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvuu76orfh/requirements.txt (line 3)) (3.5.0)
[2024-11-18T19:37:21.267+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvuu76orfh/requirements.txt (line 1)) (1.26.18)
[2024-11-18T19:37:21.269+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.5 in /home/***/.local/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas==2.0.3->-r /tmp/venvuu76orfh/requirements.txt (line 2)) (1.16.0)
[2024-11-18T19:37:21.416+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T19:37:21.417+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T19:37:21.422+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T19:37:22.168+0000] {process_utils.py:190} INFO - Installing collected packages: botocore, s3transfer, boto3
[2024-11-18T19:37:22.169+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T19:37:22.169+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T19:37:22.169+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvuu76orfh
[2024-11-18T19:37:22.170+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T19:37:22.580+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T19:37:22.581+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T19:37:22.581+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvuu76orfh
[2024-11-18T19:37:22.582+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T19:37:22.607+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T19:37:22.608+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T19:37:22.608+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvuu76orfh
[2024-11-18T19:37:22.609+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T19:37:22.650+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T19:37:22.651+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T19:37:22.651+0000] {process_utils.py:190} INFO - Successfully installed boto3-1.28.0 botocore-1.31.85 s3transfer-0.6.2
[2024-11-18T19:37:22.714+0000] {process_utils.py:190} INFO - 
[2024-11-18T19:37:22.715+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 24.2 -> 24.3.1
[2024-11-18T19:37:22.715+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T19:37:22.812+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvuu76orfh/bin/python /tmp/venv-calllldgnpjl/script.py /tmp/venv-calllldgnpjl/script.in /tmp/venv-calllldgnpjl/script.out /tmp/venv-calllldgnpjl/string_args.txt /tmp/venv-calllldgnpjl/termination.log
[2024-11-18T19:37:22.816+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T19:37:24.354+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T19:37:24.354+0000] {process_utils.py:190} INFO -   File "/tmp/venv-calllldgnpjl/script.py", line 101, in <module>
[2024-11-18T19:37:24.355+0000] {process_utils.py:190} INFO -     res = preprocess_and_split(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T19:37:24.355+0000] {process_utils.py:190} INFO -   File "/tmp/venv-calllldgnpjl/script.py", line 77, in preprocess_and_split
[2024-11-18T19:37:24.356+0000] {process_utils.py:190} INFO -     s3_client.put_object(Bucket="data", Key='data_info/spotify_scaler.json', Body=scaler_json)
[2024-11-18T19:37:24.356+0000] {process_utils.py:190} INFO - UnboundLocalError: local variable 's3_client' referenced before assignment
[2024-11-18T19:37:24.555+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
local variable 's3_client' referenced before assignment
[2024-11-18T19:37:24.559+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spotify_recommender_dag_v3, task_id=preprocess_and_split, execution_date=20241118T193712, start_date=20241118T193718, end_date=20241118T193724
[2024-11-18T19:37:24.569+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 111 for task preprocess_and_split (Process returned non-zero exit status 1.
local variable 's3_client' referenced before assignment; 820)
[2024-11-18T19:37:24.585+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T19:37:24.597+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
