[2024-11-18T18:19:42.895+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:14:14.799089+00:00 [queued]>
[2024-11-18T18:19:42.900+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:14:14.799089+00:00 [queued]>
[2024-11-18T18:19:42.900+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2024-11-18T18:19:42.907+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): train_challenger_model> on 2024-11-18 18:14:14.799089+00:00
[2024-11-18T18:19:42.910+0000] {standard_task_runner.py:60} INFO - Started process 9624 to run task
[2024-11-18T18:19:42.911+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spotify_retrain_challenge_model_v3', 'train_challenger_model', 'manual__2024-11-18T18:14:14.799089+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/retrain_music_model.py', '--cfg-path', '/tmp/tmpbtg81k0f']
[2024-11-18T18:19:42.913+0000] {standard_task_runner.py:88} INFO - Job 80: Subtask train_challenger_model
[2024-11-18T18:19:42.938+0000] {task_command.py:423} INFO - Running <TaskInstance: spotify_retrain_challenge_model_v3.train_challenger_model manual__2024-11-18T18:14:14.799089+00:00 [running]> on host 98017b53a184
[2024-11-18T18:19:42.976+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mart√≠n Horn' AIRFLOW_CTX_DAG_ID='spotify_retrain_challenge_model_v3' AIRFLOW_CTX_TASK_ID='train_challenger_model' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T18:14:14.799089+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T18:14:14.799089+00:00'
[2024-11-18T18:19:42.977+0000] {process_utils.py:182} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvc4i7fa_5 --system-site-packages --python=python
[2024-11-18T18:19:42.982+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:19:43.312+0000] {process_utils.py:190} INFO - created virtual environment CPython3.8.18.final.0-64 in 122ms
[2024-11-18T18:19:43.312+0000] {process_utils.py:190} INFO -   creator CPython3Posix(dest=/tmp/venvc4i7fa_5, clear=False, no_vcs_ignore=False, global=True)
[2024-11-18T18:19:43.312+0000] {process_utils.py:190} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-11-18T18:19:43.312+0000] {process_utils.py:190} INFO -     added seed packages: pip==23.3.1, setuptools==69.0.2, wheel==0.42.0
[2024-11-18T18:19:43.312+0000] {process_utils.py:190} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-11-18T18:19:43.329+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvc4i7fa_5/bin/pip install -r /tmp/venvc4i7fa_5/requirements.txt
[2024-11-18T18:19:43.333+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:19:44.267+0000] {process_utils.py:190} INFO - Collecting boto3==1.28.0 (from -r /tmp/venvc4i7fa_5/requirements.txt (line 1))
[2024-11-18T18:19:44.268+0000] {process_utils.py:190} INFO -   Using cached boto3-1.28.0-py3-none-any.whl.metadata (6.6 kB)
[2024-11-18T18:19:44.308+0000] {process_utils.py:190} INFO - Collecting mlflow==2.10.2 (from -r /tmp/venvc4i7fa_5/requirements.txt (line 2))
[2024-11-18T18:19:44.310+0000] {process_utils.py:190} INFO -   Using cached mlflow-2.10.2-py3-none-any.whl.metadata (13 kB)
[2024-11-18T18:19:44.311+0000] {process_utils.py:190} INFO - Requirement already satisfied: pandas==2.0.3 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvc4i7fa_5/requirements.txt (line 3)) (2.0.3)
[2024-11-18T18:19:44.312+0000] {process_utils.py:190} INFO - Requirement already satisfied: scikit-learn==1.3.2 in /home/***/.local/lib/python3.8/site-packages (from -r /tmp/venvc4i7fa_5/requirements.txt (line 4)) (1.3.2)
[2024-11-18T18:19:44.415+0000] {process_utils.py:190} INFO - Collecting tensorflow==2.13.0 (from -r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:44.417+0000] {process_utils.py:190} INFO -   Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.4 kB)
[2024-11-18T18:19:44.841+0000] {process_utils.py:190} INFO - Collecting botocore<1.32.0,>=1.31.0 (from boto3==1.28.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 1))
[2024-11-18T18:19:44.843+0000] {process_utils.py:190} INFO -   Using cached botocore-1.31.85-py3-none-any.whl.metadata (6.1 kB)
[2024-11-18T18:19:44.844+0000] {process_utils.py:190} INFO - Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /home/***/.local/lib/python3.8/site-packages (from boto3==1.28.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 1)) (0.10.0)
[2024-11-18T18:19:44.868+0000] {process_utils.py:190} INFO - Collecting s3transfer<0.7.0,>=0.6.0 (from boto3==1.28.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 1))
[2024-11-18T18:19:44.869+0000] {process_utils.py:190} INFO -   Using cached s3transfer-0.6.2-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:19:44.919+0000] {process_utils.py:190} INFO - Requirement already satisfied: click<9,>=7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (8.1.7)
[2024-11-18T18:19:44.919+0000] {process_utils.py:190} INFO - Requirement already satisfied: cloudpickle<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (3.1.0)
[2024-11-18T18:19:44.937+0000] {process_utils.py:190} INFO - Collecting entrypoints<1 (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2))
[2024-11-18T18:19:44.938+0000] {process_utils.py:190} INFO -   Using cached entrypoints-0.4-py3-none-any.whl.metadata (2.6 kB)
[2024-11-18T18:19:44.939+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitpython<4,>=2.1.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (3.1.43)
[2024-11-18T18:19:44.939+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyyaml<7,>=5.1 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (6.0.1)
[2024-11-18T18:19:44.940+0000] {process_utils.py:190} INFO - Requirement already satisfied: protobuf<5,>=3.12.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (4.25.2)
[2024-11-18T18:19:44.940+0000] {process_utils.py:190} INFO - Requirement already satisfied: pytz<2024 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (2023.3.post1)
[2024-11-18T18:19:44.941+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests<3,>=2.17.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (2.31.0)
[2024-11-18T18:19:44.941+0000] {process_utils.py:190} INFO - Requirement already satisfied: packaging<24 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (23.2)
[2024-11-18T18:19:44.942+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-metadata!=4.7.0,<8,>=3.7.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (6.11.0)
[2024-11-18T18:19:44.942+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlparse<1,>=0.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (0.4.4)
[2024-11-18T18:19:44.943+0000] {process_utils.py:190} INFO - Requirement already satisfied: alembic!=1.10.0,<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (1.13.1)
[2024-11-18T18:19:44.944+0000] {process_utils.py:190} INFO - Requirement already satisfied: docker<8,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (7.0.0)
[2024-11-18T18:19:44.944+0000] {process_utils.py:190} INFO - Requirement already satisfied: Flask<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (2.2.5)
[2024-11-18T18:19:44.945+0000] {process_utils.py:190} INFO - Requirement already satisfied: numpy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (1.24.4)
[2024-11-18T18:19:44.945+0000] {process_utils.py:190} INFO - Requirement already satisfied: scipy<2 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (1.10.1)
[2024-11-18T18:19:44.961+0000] {process_utils.py:190} INFO - Collecting querystring-parser<2 (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2))
[2024-11-18T18:19:44.962+0000] {process_utils.py:190} INFO -   Using cached querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
[2024-11-18T18:19:44.963+0000] {process_utils.py:190} INFO - Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (1.4.51)
[2024-11-18T18:19:44.964+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyarrow<16,>=4.0.0 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (14.0.2)
[2024-11-18T18:19:44.964+0000] {process_utils.py:190} INFO - Requirement already satisfied: markdown<4,>=3.3 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (3.5.2)
[2024-11-18T18:19:44.965+0000] {process_utils.py:190} INFO - Requirement already satisfied: matplotlib<4 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (3.7.5)
[2024-11-18T18:19:44.966+0000] {process_utils.py:190} INFO - Requirement already satisfied: gunicorn<22 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (21.2.0)
[2024-11-18T18:19:44.967+0000] {process_utils.py:190} INFO - Requirement already satisfied: Jinja2<4,>=2.11 in /home/***/.local/lib/python3.8/site-packages (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (3.1.3)
[2024-11-18T18:19:45.020+0000] {process_utils.py:190} INFO - Requirement already satisfied: python-dateutil>=2.8.2 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvc4i7fa_5/requirements.txt (line 3)) (2.8.2)
[2024-11-18T18:19:45.021+0000] {process_utils.py:190} INFO - Requirement already satisfied: tzdata>=2022.1 in /home/***/.local/lib/python3.8/site-packages (from pandas==2.0.3->-r /tmp/venvc4i7fa_5/requirements.txt (line 3)) (2023.4)
[2024-11-18T18:19:45.040+0000] {process_utils.py:190} INFO - Requirement already satisfied: joblib>=1.1.1 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 4)) (1.4.2)
[2024-11-18T18:19:45.041+0000] {process_utils.py:190} INFO - Requirement already satisfied: threadpoolctl>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from scikit-learn==1.3.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 4)) (3.5.0)
[2024-11-18T18:19:45.074+0000] {process_utils.py:190} INFO - Collecting absl-py>=1.0.0 (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:45.075+0000] {process_utils.py:190} INFO -   Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
[2024-11-18T18:19:45.091+0000] {process_utils.py:190} INFO - Collecting astunparse>=1.6.0 (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:45.093+0000] {process_utils.py:190} INFO -   Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
[2024-11-18T18:19:45.253+0000] {process_utils.py:190} INFO - Collecting flatbuffers>=23.1.21 (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:45.255+0000] {process_utils.py:190} INFO -   Using cached flatbuffers-24.3.25-py2.py3-none-any.whl.metadata (850 bytes)
[2024-11-18T18:19:45.275+0000] {process_utils.py:190} INFO - Collecting gast<=0.4.0,>=0.2.1 (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:45.276+0000] {process_utils.py:190} INFO -   Using cached gast-0.4.0-py3-none-any.whl.metadata (1.1 kB)
[2024-11-18T18:19:45.294+0000] {process_utils.py:190} INFO - Collecting google-pasta>=0.1.1 (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:45.295+0000] {process_utils.py:190} INFO -   Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
[2024-11-18T18:19:45.295+0000] {process_utils.py:190} INFO - Requirement already satisfied: grpcio<2.0,>=1.24.3 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5)) (1.60.0)
[2024-11-18T18:19:45.337+0000] {process_utils.py:190} INFO - Collecting h5py>=2.9.0 (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:45.339+0000] {process_utils.py:190} INFO -   Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
[2024-11-18T18:19:45.366+0000] {process_utils.py:190} INFO - Collecting keras<2.14,>=2.13.1 (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:45.368+0000] {process_utils.py:190} INFO -   Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
[2024-11-18T18:19:45.388+0000] {process_utils.py:190} INFO - Collecting libclang>=13.0.0 (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:45.389+0000] {process_utils.py:190} INFO -   Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl.metadata (5.2 kB)
[2024-11-18T18:19:45.537+0000] {process_utils.py:190} INFO - Collecting numpy<2 (from mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2))
[2024-11-18T18:19:45.538+0000] {process_utils.py:190} INFO -   Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
[2024-11-18T18:19:45.555+0000] {process_utils.py:190} INFO - Collecting opt-einsum>=2.3.2 (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:45.556+0000] {process_utils.py:190} INFO -   Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
[2024-11-18T18:19:45.557+0000] {process_utils.py:190} INFO - Requirement already satisfied: setuptools in /tmp/venvc4i7fa_5/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5)) (69.0.2)
[2024-11-18T18:19:45.557+0000] {process_utils.py:190} INFO - Requirement already satisfied: six>=1.12.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:19:45.583+0000] {process_utils.py:190} INFO - Collecting tensorboard<2.14,>=2.13 (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:45.584+0000] {process_utils.py:190} INFO -   Using cached tensorboard-2.13.0-py3-none-any.whl.metadata (1.8 kB)
[2024-11-18T18:19:45.602+0000] {process_utils.py:190} INFO - Collecting tensorflow-estimator<2.14,>=2.13.0 (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:45.604+0000] {process_utils.py:190} INFO -   Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl.metadata (1.3 kB)
[2024-11-18T18:19:45.604+0000] {process_utils.py:190} INFO - Requirement already satisfied: termcolor>=1.1.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5)) (2.4.0)
[2024-11-18T18:19:45.665+0000] {process_utils.py:190} INFO - Collecting typing-extensions<4.6.0,>=3.6.6 (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:45.667+0000] {process_utils.py:190} INFO -   Using cached typing_extensions-4.5.0-py3-none-any.whl.metadata (8.5 kB)
[2024-11-18T18:19:45.668+0000] {process_utils.py:190} INFO - Requirement already satisfied: wrapt>=1.11.0 in /home/***/.local/lib/python3.8/site-packages (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5)) (1.16.0)
[2024-11-18T18:19:45.702+0000] {process_utils.py:190} INFO - Collecting tensorflow-io-gcs-filesystem>=0.23.1 (from tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:45.703+0000] {process_utils.py:190} INFO -   Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (14 kB)
[2024-11-18T18:19:45.710+0000] {process_utils.py:190} INFO - Requirement already satisfied: Mako in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (1.3.0)
[2024-11-18T18:19:45.715+0000] {process_utils.py:190} INFO - Requirement already satisfied: importlib-resources in /home/***/.local/lib/python3.8/site-packages (from alembic!=1.10.0,<2->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (5.13.0)
[2024-11-18T18:19:45.717+0000] {process_utils.py:190} INFO - Requirement already satisfied: wheel<1.0,>=0.23.0 in /tmp/venvc4i7fa_5/lib/python3.8/site-packages (from astunparse>=1.6.0->tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5)) (0.42.0)
[2024-11-18T18:19:45.722+0000] {process_utils.py:190} INFO - Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/***/.local/lib/python3.8/site-packages (from botocore<1.32.0,>=1.31.0->boto3==1.28.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 1)) (1.26.18)
[2024-11-18T18:19:45.736+0000] {process_utils.py:190} INFO - Requirement already satisfied: Werkzeug>=2.2.2 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (2.2.3)
[2024-11-18T18:19:45.737+0000] {process_utils.py:190} INFO - Requirement already satisfied: itsdangerous>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Flask<4->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (2.1.2)
[2024-11-18T18:19:45.752+0000] {process_utils.py:190} INFO - Requirement already satisfied: gitdb<5,>=4.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (4.0.11)
[2024-11-18T18:19:45.777+0000] {process_utils.py:190} INFO - Requirement already satisfied: zipp>=0.5 in /home/***/.local/lib/python3.8/site-packages (from importlib-metadata!=4.7.0,<8,>=3.7.0->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (3.17.0)
[2024-11-18T18:19:45.781+0000] {process_utils.py:190} INFO - Requirement already satisfied: MarkupSafe>=2.0 in /home/***/.local/lib/python3.8/site-packages (from Jinja2<4,>=2.11->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (2.1.3)
[2024-11-18T18:19:45.804+0000] {process_utils.py:190} INFO - Requirement already satisfied: contourpy>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (1.1.1)
[2024-11-18T18:19:45.805+0000] {process_utils.py:190} INFO - Requirement already satisfied: cycler>=0.10 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (0.12.1)
[2024-11-18T18:19:45.805+0000] {process_utils.py:190} INFO - Requirement already satisfied: fonttools>=4.22.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (4.54.1)
[2024-11-18T18:19:45.805+0000] {process_utils.py:190} INFO - Requirement already satisfied: kiwisolver>=1.0.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (1.4.7)
[2024-11-18T18:19:45.815+0000] {process_utils.py:190} INFO - Requirement already satisfied: pillow>=6.2.0 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (10.4.0)
[2024-11-18T18:19:45.815+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyparsing>=2.3.1 in /home/***/.local/lib/python3.8/site-packages (from matplotlib<4->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (3.1.1)
[2024-11-18T18:19:45.860+0000] {process_utils.py:190} INFO - Requirement already satisfied: charset-normalizer<4,>=2 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (3.3.2)
[2024-11-18T18:19:45.861+0000] {process_utils.py:190} INFO - Requirement already satisfied: idna<4,>=2.5 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (3.6)
[2024-11-18T18:19:45.862+0000] {process_utils.py:190} INFO - Requirement already satisfied: certifi>=2017.4.17 in /home/***/.local/lib/python3.8/site-packages (from requests<3,>=2.17.3->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (2023.11.17)
[2024-11-18T18:19:46.109+0000] {process_utils.py:190} INFO - Requirement already satisfied: greenlet!=0.4.17 in /home/***/.local/lib/python3.8/site-packages (from sqlalchemy<3,>=1.4.0->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (3.0.3)
[2024-11-18T18:19:46.127+0000] {process_utils.py:190} INFO - Requirement already satisfied: google-auth<3,>=1.6.3 in /home/***/.local/lib/python3.8/site-packages (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5)) (2.26.2)
[2024-11-18T18:19:46.148+0000] {process_utils.py:190} INFO - Collecting google-auth-oauthlib<1.1,>=0.5 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:46.149+0000] {process_utils.py:190} INFO -   Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl.metadata (2.7 kB)
[2024-11-18T18:19:46.180+0000] {process_utils.py:190} INFO - Collecting tensorboard-data-server<0.8.0,>=0.7.0 (from tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5))
[2024-11-18T18:19:46.181+0000] {process_utils.py:190} INFO -   Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl.metadata (1.1 kB)
[2024-11-18T18:19:46.323+0000] {process_utils.py:190} INFO - Requirement already satisfied: smmap<6,>=3.0.1 in /home/***/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=2.1.0->mlflow==2.10.2->-r /tmp/venvc4i7fa_5/requirements.txt (line 2)) (5.0.1)
[2024-11-18T18:19:46.334+0000] {process_utils.py:190} INFO - Requirement already satisfied: cachetools<6.0,>=2.0.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5)) (5.3.2)
[2024-11-18T18:19:46.334+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1-modules>=0.2.1 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5)) (0.3.0)
[2024-11-18T18:19:46.335+0000] {process_utils.py:190} INFO - Requirement already satisfied: rsa<5,>=3.1.4 in /home/***/.local/lib/python3.8/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5)) (4.9)
[2024-11-18T18:19:46.341+0000] {process_utils.py:190} INFO - Requirement already satisfied: requests-oauthlib>=0.7.0 in /home/***/.local/lib/python3.8/site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5)) (1.3.1)
[2024-11-18T18:19:46.470+0000] {process_utils.py:190} INFO - Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /home/***/.local/lib/python3.8/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5)) (0.5.1)
[2024-11-18T18:19:46.477+0000] {process_utils.py:190} INFO - Requirement already satisfied: oauthlib>=3.0.0 in /home/***/.local/lib/python3.8/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.14,>=2.13->tensorflow==2.13.0->-r /tmp/venvc4i7fa_5/requirements.txt (line 5)) (3.2.2)
[2024-11-18T18:19:46.509+0000] {process_utils.py:190} INFO - Using cached boto3-1.28.0-py3-none-any.whl (135 kB)
[2024-11-18T18:19:46.510+0000] {process_utils.py:190} INFO - Using cached mlflow-2.10.2-py3-none-any.whl (19.5 MB)
[2024-11-18T18:19:46.528+0000] {process_utils.py:190} INFO - Using cached tensorflow-2.13.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (524.1 MB)
[2024-11-18T18:19:47.003+0000] {process_utils.py:190} INFO - Using cached absl_py-2.1.0-py3-none-any.whl (133 kB)
[2024-11-18T18:19:47.005+0000] {process_utils.py:190} INFO - Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
[2024-11-18T18:19:47.006+0000] {process_utils.py:190} INFO - Using cached botocore-1.31.85-py3-none-any.whl (11.3 MB)
[2024-11-18T18:19:47.017+0000] {process_utils.py:190} INFO - Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)
[2024-11-18T18:19:47.018+0000] {process_utils.py:190} INFO - Using cached flatbuffers-24.3.25-py2.py3-none-any.whl (26 kB)
[2024-11-18T18:19:47.019+0000] {process_utils.py:190} INFO - Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
[2024-11-18T18:19:47.020+0000] {process_utils.py:190} INFO - Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
[2024-11-18T18:19:47.024+0000] {process_utils.py:190} INFO - Using cached h5py-3.11.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.3 MB)
[2024-11-18T18:19:47.027+0000] {process_utils.py:190} INFO - Using cached keras-2.13.1-py3-none-any.whl (1.7 MB)
[2024-11-18T18:19:47.030+0000] {process_utils.py:190} INFO - Using cached libclang-18.1.1-py2.py3-none-manylinux2010_x86_64.whl (24.5 MB)
[2024-11-18T18:19:47.054+0000] {process_utils.py:190} INFO - Using cached numpy-1.24.3-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.3 MB)
[2024-11-18T18:19:47.070+0000] {process_utils.py:190} INFO - Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
[2024-11-18T18:19:47.071+0000] {process_utils.py:190} INFO - Using cached querystring_parser-1.2.4-py2.py3-none-any.whl (7.9 kB)
[2024-11-18T18:19:47.072+0000] {process_utils.py:190} INFO - Using cached s3transfer-0.6.2-py3-none-any.whl (79 kB)
[2024-11-18T18:19:47.074+0000] {process_utils.py:190} INFO - Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
[2024-11-18T18:19:47.080+0000] {process_utils.py:190} INFO - Using cached tensorflow_estimator-2.13.0-py2.py3-none-any.whl (440 kB)
[2024-11-18T18:19:47.081+0000] {process_utils.py:190} INFO - Using cached tensorflow_io_gcs_filesystem-0.34.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.4 MB)
[2024-11-18T18:19:47.084+0000] {process_utils.py:190} INFO - Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
[2024-11-18T18:19:47.085+0000] {process_utils.py:190} INFO - Using cached google_auth_oauthlib-1.0.0-py2.py3-none-any.whl (18 kB)
[2024-11-18T18:19:47.087+0000] {process_utils.py:190} INFO - Using cached tensorboard_data_server-0.7.2-py3-none-manylinux_2_31_x86_64.whl (6.6 MB)
[2024-11-18T18:19:49.208+0000] {process_utils.py:190} INFO - Installing collected packages: libclang, flatbuffers, typing-extensions, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard-data-server, querystring-parser, opt-einsum, numpy, keras, google-pasta, gast, entrypoints, astunparse, absl-py, h5py, botocore, s3transfer, google-auth-oauthlib, tensorboard, mlflow, boto3, tensorflow
[2024-11-18T18:19:49.456+0000] {process_utils.py:190} INFO -   Attempting uninstall: typing-extensions
[2024-11-18T18:19:49.458+0000] {process_utils.py:190} INFO -     Found existing installation: typing_extensions 4.9.0
[2024-11-18T18:19:49.458+0000] {process_utils.py:190} INFO -     Not uninstalling typing-extensions at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvc4i7fa_5
[2024-11-18T18:19:49.458+0000] {process_utils.py:190} INFO -     Can't uninstall 'typing_extensions'. No files were found to uninstall.
[2024-11-18T18:19:49.733+0000] {process_utils.py:190} INFO -   Attempting uninstall: numpy
[2024-11-18T18:19:49.734+0000] {process_utils.py:190} INFO -     Found existing installation: numpy 1.24.4
[2024-11-18T18:19:49.734+0000] {process_utils.py:190} INFO -     Not uninstalling numpy at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvc4i7fa_5
[2024-11-18T18:19:49.735+0000] {process_utils.py:190} INFO -     Can't uninstall 'numpy'. No files were found to uninstall.
[2024-11-18T18:19:51.403+0000] {process_utils.py:190} INFO -   Attempting uninstall: botocore
[2024-11-18T18:19:51.404+0000] {process_utils.py:190} INFO -     Found existing installation: botocore 1.35.44
[2024-11-18T18:19:51.404+0000] {process_utils.py:190} INFO -     Not uninstalling botocore at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvc4i7fa_5
[2024-11-18T18:19:51.404+0000] {process_utils.py:190} INFO -     Can't uninstall 'botocore'. No files were found to uninstall.
[2024-11-18T18:19:51.803+0000] {process_utils.py:190} INFO -   Attempting uninstall: s3transfer
[2024-11-18T18:19:51.804+0000] {process_utils.py:190} INFO -     Found existing installation: s3transfer 0.10.3
[2024-11-18T18:19:51.804+0000] {process_utils.py:190} INFO -     Not uninstalling s3transfer at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvc4i7fa_5
[2024-11-18T18:19:51.805+0000] {process_utils.py:190} INFO -     Can't uninstall 's3transfer'. No files were found to uninstall.
[2024-11-18T18:19:51.826+0000] {process_utils.py:190} INFO -   Attempting uninstall: google-auth-oauthlib
[2024-11-18T18:19:51.827+0000] {process_utils.py:190} INFO -     Found existing installation: google-auth-oauthlib 1.2.0
[2024-11-18T18:19:51.828+0000] {process_utils.py:190} INFO -     Not uninstalling google-auth-oauthlib at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvc4i7fa_5
[2024-11-18T18:19:51.828+0000] {process_utils.py:190} INFO -     Can't uninstall 'google-auth-oauthlib'. No files were found to uninstall.
[2024-11-18T18:19:52.029+0000] {process_utils.py:190} INFO -   Attempting uninstall: mlflow
[2024-11-18T18:19:52.030+0000] {process_utils.py:190} INFO -     Found existing installation: mlflow 2.17.0
[2024-11-18T18:19:52.031+0000] {process_utils.py:190} INFO -     Not uninstalling mlflow at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvc4i7fa_5
[2024-11-18T18:19:52.031+0000] {process_utils.py:190} INFO -     Can't uninstall 'mlflow'. No files were found to uninstall.
[2024-11-18T18:19:52.595+0000] {process_utils.py:190} INFO -   Attempting uninstall: boto3
[2024-11-18T18:19:52.596+0000] {process_utils.py:190} INFO -     Found existing installation: boto3 1.35.44
[2024-11-18T18:19:52.596+0000] {process_utils.py:190} INFO -     Not uninstalling boto3 at /home/***/.local/lib/python3.8/site-packages, outside environment /tmp/venvc4i7fa_5
[2024-11-18T18:19:52.596+0000] {process_utils.py:190} INFO -     Can't uninstall 'boto3'. No files were found to uninstall.
[2024-11-18T18:19:59.863+0000] {process_utils.py:190} INFO - ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
[2024-11-18T18:19:59.863+0000] {process_utils.py:190} INFO - aiobotocore 2.9.0 requires botocore<1.33.14,>=1.33.2, but you have botocore 1.31.85 which is incompatible.
[2024-11-18T18:19:59.864+0000] {process_utils.py:190} INFO - azure-core 1.29.6 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:19:59.864+0000] {process_utils.py:190} INFO - azure-mgmt-keyvault 10.3.1 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:19:59.864+0000] {process_utils.py:190} INFO - azure-mgmt-network 27.0.0 requires typing-extensions>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:19:59.865+0000] {process_utils.py:190} INFO - graphene 3.4 requires typing-extensions<5,>=4.7.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:19:59.865+0000] {process_utils.py:190} INFO - pydantic 2.5.3 requires typing-extensions>=4.6.1, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:19:59.865+0000] {process_utils.py:190} INFO - pydantic-core 2.14.6 requires typing-extensions!=4.7.0,>=4.6.0, but you have typing-extensions 4.5.0 which is incompatible.
[2024-11-18T18:19:59.865+0000] {process_utils.py:190} INFO - Successfully installed absl-py-2.1.0 astunparse-1.6.3 boto3-1.28.0 botocore-1.31.85 entrypoints-0.4 flatbuffers-24.3.25 gast-0.4.0 google-auth-oauthlib-1.0.0 google-pasta-0.2.0 h5py-3.11.0 keras-2.13.1 libclang-18.1.1 mlflow-2.10.2 numpy-1.24.3 opt-einsum-3.4.0 querystring-parser-1.2.4 s3transfer-0.6.2 tensorboard-2.13.0 tensorboard-data-server-0.7.2 tensorflow-2.13.0 tensorflow-estimator-2.13.0 tensorflow-io-gcs-filesystem-0.34.0 typing-extensions-4.5.0
[2024-11-18T18:19:59.940+0000] {process_utils.py:190} INFO - 
[2024-11-18T18:19:59.940+0000] {process_utils.py:190} INFO - [notice] A new release of pip is available: 23.3.1 -> 24.3.1
[2024-11-18T18:19:59.941+0000] {process_utils.py:190} INFO - [notice] To update, run: python -m pip install --upgrade pip
[2024-11-18T18:20:00.160+0000] {process_utils.py:182} INFO - Executing cmd: /tmp/venvc4i7fa_5/bin/python /tmp/venv-call28o9q5gy/script.py /tmp/venv-call28o9q5gy/script.in /tmp/venv-call28o9q5gy/script.out /tmp/venv-call28o9q5gy/string_args.txt /tmp/venv-call28o9q5gy/termination.log
[2024-11-18T18:20:00.164+0000] {process_utils.py:186} INFO - Output:
[2024-11-18T18:20:01.114+0000] {process_utils.py:190} INFO - 2024-11-18 18:20:01.114687: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-11-18T18:20:01.115+0000] {process_utils.py:190} INFO - 2024-11-18 18:20:01.115740: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:20:01.136+0000] {process_utils.py:190} INFO - 2024-11-18 18:20:01.136644: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
[2024-11-18T18:20:01.137+0000] {process_utils.py:190} INFO - 2024-11-18 18:20:01.136914: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-11-18T18:20:01.137+0000] {process_utils.py:190} INFO - To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-11-18T18:20:01.632+0000] {process_utils.py:190} INFO - 2024-11-18 18:20:01.632007: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-11-18T18:20:02.668+0000] {process_utils.py:190} INFO - Epoch 1/10
[2024-11-18T18:20:03.575+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 3:28 - loss: 0.4080 47/575 [=>............................] - ETA: 0s - loss: 0.1448   94/575 [===>..........................] - ETA: 0s - loss: 0.1044174/575 [========>.....................] - ETA: 0s - loss: 0.0780256/575 [============>.................] - ETA: 0s - loss: 0.0645342/575 [================>.............] - ETA: 0s - loss: 0.0557426/575 [=====================>........] - ETA: 0s - loss: 0.0497504/575 [=========================>....] - ETA: 0s - loss: 0.0455575/575 [==============================] - 1s 946us/step - loss: 0.0425 - val_loss: 0.0081
[2024-11-18T18:20:03.575+0000] {process_utils.py:190} INFO - Epoch 2/10
[2024-11-18T18:20:04.025+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0209 80/575 [===>..........................] - ETA: 0s - loss: 0.0190159/575 [=======>......................] - ETA: 0s - loss: 0.0187236/575 [===========>..................] - ETA: 0s - loss: 0.0180315/575 [===============>..............] - ETA: 0s - loss: 0.0175394/575 [===================>..........] - ETA: 0s - loss: 0.0170473/575 [=======================>......] - ETA: 0s - loss: 0.0166546/575 [===========================>..] - ETA: 0s - loss: 0.0161575/575 [==============================] - 0s 782us/step - loss: 0.0160 - val_loss: 0.0051
[2024-11-18T18:20:04.025+0000] {process_utils.py:190} INFO - Epoch 3/10
[2024-11-18T18:20:04.466+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0151 84/575 [===>..........................] - ETA: 0s - loss: 0.0132167/575 [=======>......................] - ETA: 0s - loss: 0.0126249/575 [===========>..................] - ETA: 0s - loss: 0.0123329/575 [================>.............] - ETA: 0s - loss: 0.0120407/575 [====================>.........] - ETA: 0s - loss: 0.0118487/575 [========================>.....] - ETA: 0s - loss: 0.0116568/575 [============================>.] - ETA: 0s - loss: 0.0114575/575 [==============================] - 0s 768us/step - loss: 0.0114 - val_loss: 0.0039
[2024-11-18T18:20:04.467+0000] {process_utils.py:190} INFO - Epoch 4/10
[2024-11-18T18:20:04.912+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0111 78/575 [===>..........................] - ETA: 0s - loss: 0.0104154/575 [=======>......................] - ETA: 0s - loss: 0.0102229/575 [==========>...................] - ETA: 0s - loss: 0.0101307/575 [===============>..............] - ETA: 0s - loss: 0.0100390/575 [===================>..........] - ETA: 0s - loss: 0.0098474/575 [=======================>......] - ETA: 0s - loss: 0.0098553/575 [===========================>..] - ETA: 0s - loss: 0.0097575/575 [==============================] - 0s 774us/step - loss: 0.0096 - val_loss: 0.0039
[2024-11-18T18:20:04.912+0000] {process_utils.py:190} INFO - Epoch 5/10
[2024-11-18T18:20:05.353+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0095 79/575 [===>..........................] - ETA: 0s - loss: 0.0087153/575 [======>.......................] - ETA: 0s - loss: 0.0087240/575 [===========>..................] - ETA: 0s - loss: 0.0087321/575 [===============>..............] - ETA: 0s - loss: 0.0088400/575 [===================>..........] - ETA: 0s - loss: 0.0088477/575 [=======================>......] - ETA: 0s - loss: 0.0088559/575 [============================>.] - ETA: 0s - loss: 0.0088575/575 [==============================] - 0s 766us/step - loss: 0.0087 - val_loss: 0.0034
[2024-11-18T18:20:05.353+0000] {process_utils.py:190} INFO - Epoch 6/10
[2024-11-18T18:20:05.853+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0079 79/575 [===>..........................] - ETA: 0s - loss: 0.0084159/575 [=======>......................] - ETA: 0s - loss: 0.0083241/575 [===========>..................] - ETA: 0s - loss: 0.0085325/575 [===============>..............] - ETA: 0s - loss: 0.0083408/575 [====================>.........] - ETA: 0s - loss: 0.0082487/575 [========================>.....] - ETA: 0s - loss: 0.0082559/575 [============================>.] - ETA: 0s - loss: 0.0081575/575 [==============================] - 0s 869us/step - loss: 0.0081 - val_loss: 0.0032
[2024-11-18T18:20:05.853+0000] {process_utils.py:190} INFO - Epoch 7/10
[2024-11-18T18:20:06.305+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0083 75/575 [==>...........................] - ETA: 0s - loss: 0.0077155/575 [=======>......................] - ETA: 0s - loss: 0.0075234/575 [===========>..................] - ETA: 0s - loss: 0.0076310/575 [===============>..............] - ETA: 0s - loss: 0.0076387/575 [===================>..........] - ETA: 0s - loss: 0.0075463/575 [=======================>......] - ETA: 0s - loss: 0.0075544/575 [===========================>..] - ETA: 0s - loss: 0.0075575/575 [==============================] - 0s 785us/step - loss: 0.0075 - val_loss: 0.0027
[2024-11-18T18:20:06.305+0000] {process_utils.py:190} INFO - Epoch 8/10
[2024-11-18T18:20:06.749+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0087 79/575 [===>..........................] - ETA: 0s - loss: 0.0074160/575 [=======>......................] - ETA: 0s - loss: 0.0073235/575 [===========>..................] - ETA: 0s - loss: 0.0073309/575 [===============>..............] - ETA: 0s - loss: 0.0073393/575 [===================>..........] - ETA: 0s - loss: 0.0072475/575 [=======================>......] - ETA: 0s - loss: 0.0072554/575 [===========================>..] - ETA: 0s - loss: 0.0072575/575 [==============================] - 0s 771us/step - loss: 0.0072 - val_loss: 0.0024
[2024-11-18T18:20:06.749+0000] {process_utils.py:190} INFO - Epoch 9/10
[2024-11-18T18:20:07.212+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0069 77/575 [===>..........................] - ETA: 0s - loss: 0.0071151/575 [======>.......................] - ETA: 0s - loss: 0.0071221/575 [==========>...................] - ETA: 0s - loss: 0.0070294/575 [==============>...............] - ETA: 0s - loss: 0.0070369/575 [==================>...........] - ETA: 0s - loss: 0.0070450/575 [======================>.......] - ETA: 0s - loss: 0.0069537/575 [===========================>..] - ETA: 0s - loss: 0.0069575/575 [==============================] - 0s 806us/step - loss: 0.0069 - val_loss: 0.0024
[2024-11-18T18:20:07.213+0000] {process_utils.py:190} INFO - Epoch 10/10
[2024-11-18T18:20:07.672+0000] {process_utils.py:190} INFO -   1/575 [..............................] - ETA: 0s - loss: 0.0093 78/575 [===>..........................] - ETA: 0s - loss: 0.0068160/575 [=======>......................] - ETA: 0s - loss: 0.0068234/575 [===========>..................] - ETA: 0s - loss: 0.0068307/575 [===============>..............] - ETA: 0s - loss: 0.0068386/575 [===================>..........] - ETA: 0s - loss: 0.0069456/575 [======================>.......] - ETA: 0s - loss: 0.0068533/575 [==========================>...] - ETA: 0s - loss: 0.0068575/575 [==============================] - 0s 799us/step - loss: 0.0068 - val_loss: 0.0024
[2024-11-18T18:20:08.078+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 29s101/719 [===>..........................] - ETA: 0s 213/719 [=======>......................] - ETA: 0s321/719 [============>.................] - ETA: 0s420/719 [================>.............] - ETA: 0s522/719 [====================>.........] - ETA: 0s630/719 [=========================>....] - ETA: 0s719/719 [==============================] - 0s 478us/step
[2024-11-18T18:20:08.640+0000] {process_utils.py:190} INFO -   1/719 [..............................] - ETA: 7s100/719 [===>..........................] - ETA: 0s206/719 [=======>......................] - ETA: 0s304/719 [===========>..................] - ETA: 0s407/719 [===============>..............] - ETA: 0s512/719 [====================>.........] - ETA: 0s614/719 [========================>.....] - ETA: 0s719/719 [==============================] - 0s 488us/step
[2024-11-18T18:20:08.737+0000] {process_utils.py:190} INFO - /tmp/venvc4i7fa_5/lib/python3.8/site-packages/keras/src/engine/training.py:3000 UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
[2024-11-18T18:20:08.759+0000] {process_utils.py:190} INFO - Traceback (most recent call last):
[2024-11-18T18:20:08.759+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call28o9q5gy/script.py", line 100, in <module>
[2024-11-18T18:20:08.759+0000] {process_utils.py:190} INFO -     res = train_challenger_model(*arg_dict["args"], **arg_dict["kwargs"])
[2024-11-18T18:20:08.760+0000] {process_utils.py:190} INFO -   File "/tmp/venv-call28o9q5gy/script.py", line 83, in train_challenger_model
[2024-11-18T18:20:08.760+0000] {process_utils.py:190} INFO -     mlflow.tensorflow.log_model(
[2024-11-18T18:20:08.760+0000] {process_utils.py:190} INFO - TypeError: log_model() got an unexpected keyword argument 'tf_saved_model_dir'
[2024-11-18T18:20:09.665+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 400, in execute
    return super().execute(context=serializable_context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 716, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 471, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
log_model() got an unexpected keyword argument 'tf_saved_model_dir'
[2024-11-18T18:20:09.668+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=spotify_retrain_challenge_model_v3, task_id=train_challenger_model, execution_date=20241118T181414, start_date=20241118T181942, end_date=20241118T182009
[2024-11-18T18:20:09.674+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 80 for task train_challenger_model (Process returned non-zero exit status 1.
log_model() got an unexpected keyword argument 'tf_saved_model_dir'; 9624)
[2024-11-18T18:20:09.686+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-11-18T18:20:09.697+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
